### ISSUE TITLE
Symbol: backup_src_start not found cannot set

### ISSUE THREAD

**Issue by coldnew** [alef78/x86_ramos_i9_kexec_tools#1]
Have you success on this kexec-tool ? I hac try kexec-tool with patch you mention in df9bf9f , but it throw following error

```
Symbol: backup_src_start not found cannot set
```

My device (Geeksphone Revolution with Intel Atom Z2560) is enable kexec in kernel, since it lock the boot.img, I am trying to figure out method to make my own kernel and ramdisk work. 

My kexec-tool with Android.mk here:
https://github.com/coldnew-gp-revolution/kexec-tools/blob/revolution-2.0.10/Android.mk

**Comment by alef78** [comment]
Yes, on my Ramos i9 (with Intel Atom Z2580, linux kernel version 3.10.20) it works. I have not seen backup_src_start error. My patch simply set correct subarch for kexec'ed kernel - without that, kernel halts at boot very early.

**Comment by alef78** [comment]
I added statically linked kexec to this repository, that works for me.

**Comment by coldnew** [comment]
hmm... I'll figure what's the problem, maybe it is caused by linux kernel version (Geeksphone's kernel is 3.4.43)

do you use follwing command to run kexec ?

```
kexec -l bzImage --ramdisk=ramdisk.cpio.gz --reuse-cmdline
kexec -e
```

thanks for your help :)

**Comment by alef78** [comment]
I usually use 

```
kexec -l -d bzImage --ramdisk=ramdisk.cpio.gz --reuse-cmdline
kexec -e
```

With -d switch kexec shows what it is doing. And if device halts after kexec -e, that means kexec is working and starting a new kernel, which then halts somewhere. Original kernel may need some patches in order to boot after kexec (on Ramos i9 I had to add patch for switching display power off/on during kernel boot).

**Comment by coldnew** [comment]
Now I think the problem is my kernel lack of some patch you remind, I'll try it. Anyway, many thanks for your help :) 

PS: Your tool didn't show the `Symbol: backup_src_start not found cannot set` error, so I'll try to rebase mine to more stable version of kexec-tool.

**Comment by coldnew** [comment]
Something I forget to mention is that aftet `kexec -e`, the system is halt, but  after some while, the whole system reboot, and the message in `/proc/version` dosen't change to mine kernel info (which means it still go back to original kernel or the watchdog trigger cpu to reset)

**Comment by alef78** [comment]
When kernel halts, watchdog reboots the system (after about 60-70seconds on my tablet).
You may try to use this patch for the kernel: https://github.com/alef78/x86_ramos_i9_kernel/commit/188a6bfe6092a6bbc5e7fdf82284b76a63db7776
It logs kernel boot messages to RAM buffer at physical address 0xA0000 (that is address space of legacy vga adapter, not used on Intel Mid platform.). On Ramos i9, contents of this memory is preserved when device is rebooted by watchdog. So I was able to debug kernel boot by the following:
1. apply the patch, enable EARLY_PRINTK_VGAMEM_HACK kernel config option added by it.
2. clear legacy VGA memory buffer:

```
dd if=/dev/zero of=/dev/mem seek=655360 bs=1 count=97016
```
1. try to boot patched kernel with kexec
2. after device rebooted by watchdog timer, check contents of that memory buffer by

```
dd if=/dev/mem of=log.txt bs=1 count=97000 skip=655376
less log.txt
```

it should show "Uncompressing kernel...", etc. I am not sure it this works on your device (it depends if on your device that memory contents is preserved after reboot), but if  it works, it should help debug kexec'ed kernel boot.

**Comment by coldnew** [comment]
Hi @alef78 , 
thank you for your advice, I'll try it and let you know if I success or not.
But I think I need some time to backport this, since my kernel 3.4 dosent has the log_store in printk.c :(

**Comment by alef78** [comment]
Patching only  kernel/arch/x86/boot/compressed/misc.c  should be enough to see at least "Decompressing Linux ... done. Booting the kernel", you may try that before backporting the rest of the patch.
